### ISSUE TITLE
LBN not working with new Tensorflow

### ISSUE THREAD

**Issue by NiclasEich** [riga/LBN#4]
The lbn breaks in the newest version of tensorflow, at leat on my machine:

I don't have time right now, but can investigate soon what is happening there.

```
NiclasEich@my-machine:~$ ipython
Python 3.8.5 (default, Jan 27 2021, 15:41:15)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tensorflow as tf
   ...: import lbn
   ...: from lbn import LBN, LBNLayer
   ...:
   ...: print("LBN-version: ", lbn.__version__)
   ...: print("tf-version: ", tf.__version__)
   ...:
   ...: # start a sequential model
   ...: model = tf.keras.models.Sequential()
   ...:
   ...: # add the LBN layer
   ...: input_shape = (6, 4)
   ...: model.add(LBNLayer(input_shape, 10, boost_mode=LBN.PAIRS))
   ...:
   ...: # add a dense layer
   ...: model.add(tf.keras.layers.Dense(1024))
LBN-version:  1.2.1
tf-version:  2.4.1
2021-04-27 12:58:04.058275: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-94011a21aae4> in <module>
     11 # add the LBN layer
     12 input_shape = (6, 4)
---> 13 model.add(LBNLayer(input_shape, 10, boost_mode=LBN.PAIRS))
     14
     15 # add a dense layer

/software/python/lib/python3.8/site-packages/lbn.py in __init__(self, input_shape, *args, **kwargs)
    919
    920         # the input_shape is mandatory so we can build right away
--> 921         self.build(input_shape)
    922
    923         # layer init

/software/python/lib/python3.8/site-packages/lbn.py in build(self, input_shape)
    927     def build(self, input_shape):
    928         # build the lbn
--> 929         self.lbn.build(input_shape, features=self._features,
    930             external_features=self._external_features)
    931

/software/python/lib/python3.8/site-packages/lbn.py in build(self, input_shape, features, external_features)
    258         self.n_features = 0
    259         # lbn features
--> 260         for feature in features:
    261             self.n_features += self.feature_factory._feature_funcs[feature]._shape_func(self.n_out)
    262         # auxiliary features

TypeError: 'NoneType' object is not iterable
```

**Comment by riga** [comment]
Thanks for reporting @NiclasEich !
Should be fixed in the master now. There are a few warnings from autograph not being able to convert certain setup methods, but this should be fine as the heavy-lifting seems to be covered.
Feel free to close once you gave it a spin.

**Comment by NiclasEich** [comment]
Thanks for the fix Marcel, it now works again.
